version: "2"
services:
  web:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - .:/edx/app:delegated
      - notused:/edx/app/node_modules
    ports:
      - "8734:8734"
    environment:
      - NODE_ENV=development

volumes:
  notused:
